### ISSUE TITLE
(GO-S0902) Audit required: Insecure gRPC server

### ISSUE THREAD

**Issue by scabanasm** [indykite/indykite-sdk-go#231]
## Description
gRPC is designed to work with various authentication mechanisms, making it easy to use gRPC to talk to other systems. It is recommended to use the supported authentication mechanisms to shield against multiple types of attacks (e.g., MITM - Man in the Middle Attack).

## Occurrences
There are 2 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [app.deepsource.com/gh/indykite/indykite-sdk-go/issue/GO-S0902/occurrences/](https://app.deepsource.com/gh/indykite/indykite-sdk-go/issue/GO-S0902/occurrences/)

**Comment by arxeiss** [comment]
Both occurrences are in test files. So we don't have to issue local certificate just to run unit test.
Can we exclude test files from analysis?

**Comment by scabanasm** [comment]
Test files about to be excluded from the analysis - ticket closed
